services:
  postgres:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: lostandfound_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 15s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: lostandfound_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: lostandfound_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  migrate:
    image: migrate/migrate
    container_name: lostandfound_migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://admin:admin@postgres:5432/postgres?sslmode=disable",
      "up"
    ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: LostAndFoundApp
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: [ "go", "run", "./cmd/server/main.go" ]
    environment:
      - DB_URL=postgres://admin:admin@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://lostandfound_redis:6379
      - MINIO_ENDPOINT=http://lostandfound_minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
  minio_data: